name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Init project
        run: npm init -y

      - name: Cypress run
        uses: cypress-io/github-action@v2
